// Package contract handles generating and validating tinker.toml files.
package contract

import (
	"fmt"
	"os"
	"strings"

	"github.com/mvaliolahi/tinker/internal/detect"
)

// GenerateTinkerToml creates a tinker.toml file from detection results.
func GenerateTinkerToml(result *detect.DetectionResult, projectDir string) error {
	var sb strings.Builder

	sb.WriteString("# Tinker Configuration File\n")
	sb.WriteString("# Generated by `tinker init` — edit to match your project\n")
	sb.WriteString("# See: https://github.com/mvaliolahi/tinker for full documentation\n\n")

	if result.Database != nil {
		sb.WriteString("[database]\n")
		sb.WriteString(fmt.Sprintf("source = \"%s\"\n", result.Database.Source))
		sb.WriteString(fmt.Sprintf("type = \"%s\"\n", result.Database.Type))
		sb.WriteString("\n")
	}

	if result.API != nil {
		sb.WriteString("[api]\n")
		if result.API.BaseURL != "" {
			sb.WriteString(fmt.Sprintf("base_url = \"%s\"\n", result.API.BaseURL))
		}
		if result.API.Spec != "" {
			sb.WriteString(fmt.Sprintf("spec = \"%s\"\n", result.API.Spec))
		}
		if result.API.Auth != "" {
			sb.WriteString(fmt.Sprintf("auth = \"%s\"\n", result.API.Auth))
		}
		if result.API.AuthType != "" {
			sb.WriteString(fmt.Sprintf("auth_type = \"%s\"\n", result.API.AuthType))
		}
		sb.WriteString("\n")
	}

	if result.GRPC != nil {
		sb.WriteString("[grpc]\n")
		if result.GRPC.Addr != "" {
			sb.WriteString(fmt.Sprintf("addr = \"%s\"\n", result.GRPC.Addr))
		}
		if result.GRPC.ProtoDir != "" {
			sb.WriteString(fmt.Sprintf("proto_dir = \"%s\"\n", result.GRPC.ProtoDir))
		}
		if result.GRPC.Reflection {
			sb.WriteString("reflection = true\n")
		}
		sb.WriteString("\n")
	}

	// Add a commands section template
	sb.WriteString("# [commands]\n")
	sb.WriteString("# migrate = \"go run ./cmd/migrate\"\n")
	sb.WriteString("# seed = \"go run ./cmd/seed\"\n")
	sb.WriteString("# test = \"go test ./...\"\n")
	sb.WriteString("\n")

	outputPath := fmt.Sprintf("%s/tinker.toml", projectDir)
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing tinker.toml: %w", err)
	}

	return nil
}
